version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cmsystem
    restart: always
  web:
    build: ./server
    environment:
      MYSQL_DATABASE: cmsystem
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "5001:5001"
    depends_on:
      - db
    restart: on-failure
    