version: "3.8"
services:
  db:
    image: mysql:8.1
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cmsystem
    ports:
      - "3307:3306"
    restart: always
  server:
    build: ./server
    environment:
      MYSQL_DATABASE: cmsystem
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "5001:5001"
    depends_on:
      - db
    # restart: on-failure
